project: rancher
region: ap-northeast-1
os: Ubuntu
os_version: 20.04

# User ssh to server
ansible_ssh_user: ubuntu
# User deploy
deploy_user: deploy
# General path
auth_log_path: /var/log/auth.log
sys_log_path: /var/log/syslog

#Roles/nginx
root_dir: "{{ app_dir }}/current/public"
nginx_conf_dir: "/etc/nginx"
nginx_log_dir: "/var/log/nginx"
nginx_access_log_path: "{{ nginx_log_dir }}/access.log"
nginx_error_log_path: "{{ nginx_log_dir }}/error.log"
app_nginx_access_log_path: "{{ nginx_log_dir }}/{{ server_name }}.access.log"
app_nginx_error_log_path: "{{ nginx_log_dir }}/{{ server_name }}.error.log"

# Roles/base
base_timezone: Asia/Tokyo
base_maxopenfile: 65535

# Roles/aws-cli
python_version: 3.8

# Roles/nginx
app_dir: "/var/app"
