# Install the nginx packages for Ubuntu target
- name: NGINX > Install nginx
  apt:
    name: nginx
    update-cache: yes
  become: true

- name: NGINX > Check nginx status
  shell: bash -lc "systemctl status nginx"
  register: nginx_status
- debug: var=nginx_status.stdout_lines

- name: NGINX > Copy configuration files "nginx.conf"
  template:
    src: nginx.conf.j2
    dest: "{{ nginx_conf_dir }}/nginx.conf"
    owner: root
    group: root
    mode: 0644
  become: true

# Enable Nginx
- name: NGINX > Enable service nginx
  systemd:
    name: nginx
    enabled: yes
  become: true

#https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-20-04
# Create config nginx
- name: NGINX --> Copy {{ env }}-{{ type }}-config.conf file to {{ nginx_conf_dir }}/sites-available
  template:
    src: "{{ env }}-{{ type }}-config.conf.j2"
    dest: "{{nginx_conf_dir}}/sites-available/{{ type }}-config.conf"
    owner: root
    group: root
    mode: 0644
  become: true

# Restart Nginx
- name: NGINX > Restart nginx
  service:
    name: nginx
    state: restarted
  become: true
