# Install prerequisite packages
- name : DOCKER > Install prerequisite packages  
  apt:
    name: "{{ item }}"
    state: latest
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - software-properties-common
  become: yes

# Add the GPG key for the official Docker repository to your system
- name: DOCKER > Add the GPG key for the official Docker repository
  shell: 'curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -'

# Add the Docker repository to APT sources for ubuntu 20.04
- name: DOCKER > Add the Docker repository to APT sources
  become: yes
  apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
      state: present

# Install docker-ce
- name : DOCKER > Install docker-ce
  apt:
    name: docker-ce
    state: latest
  become: yes

# Add user deploy to group docker
- name: DOCKER > Adding existing user "{{ deploy_user }}" to group docker
  user:
    name: "{{ deploy_user }}"
    groups: docker
    append: yes
  become: yes