- hosts: tag_Role_mgmt

  remote_user: "{{ ansible_ssh_user }}"
  become_method: sudo
  gather_facts: yes

  roles:
    - base
    - disable-auto-upgrade #Disable Automatically update/upgrade
    - hostname
    - ssh-users
    - distribute-key
    # - nginx
    # - mysql-server
    # - redis
    - logrotate